version: 2

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
        requires:
          - build

jobs:
  build:
    docker:
      - image: rikorose/gcc-cmake
    steps:
      - checkout
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    docker:
      - image: rikorose/gcc-cmake
    steps:
      - checkout
      - attach workspace:
          at: .
      - run:
          name: test
          command: |
            cd build
