version: 2
jobs:
  build:
    docker:
      - image: lyrahgames/cpp-test-tools:latest
    steps:
      - checkout
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    docker:
      - image: lyrahgames/cpp-test-tools:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: |
            cd build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
